import Navbar from '../components/navbar'
import NavbarContainer from '../components/navbarContainer'
import NavbarProvider from '../components/navbarProvider'
import QueryProvider from '../components/queryProvider'
import { getSession } from '../lib/session'

import './global.css';

// export const metadata = {
//   title: 'Welcome to web',
//   description: 'Generated by create-nx-workspace',
// };

export default async  function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession()
  return (
    <html lang="en">
      <body className='bg-gradient-to-b to-gray-800 from-cyan-900 text-white'>
        <QueryProvider>
          <NavbarProvider >
            <NavbarContainer user={session?.user}>
              <Navbar />
            </NavbarContainer>
          </NavbarProvider>
          {children}
        </QueryProvider>

        </body>
    </html>
  );
}
