import Navbar from '../components/navbar'
import NavbarContainer from '../components/navbarContainer'
import StoreProvider from '../components/providers/storeProvider'
import QueryProvider from '../components/providers/queryProvider'
import { getSession } from '../lib/session'

import './global.css';
import { Toaster } from 'sonner'

// export const metadata = {
//   title: 'Welcome to web',
//   description: 'Generated by create-nx-workspace',
// };

export default async  function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession()
  return (
    <html lang="en">
      <body className='bg-gradient-to-b to-gray-800 from-cyan-900 text-white'>
        <QueryProvider>
          <StoreProvider >
            <NavbarContainer user={session?.user}>
              <Navbar />
            </NavbarContainer>
          {children}
          <Toaster />
          </StoreProvider>
        </QueryProvider>

        </body>
    </html>
  );
}
